import CustomTable from "../../Component/CustomTable";
import CustomPageHeader from "../../Component/CustomPageHeader";
import ReusableInput from "../../Component/ReusableInput";
import CustomDropdown from "../../Component/CustomDropdown";
import {Box,Button,Card,CardContent,IconButton,Table,TableBody,TableCell,TableHead,TableRow,TextField,Typography} from '@mui/material';import AddIcon from '@mui/icons-material/Add';import EditIcon from '@mui/icons-material/Edit';import VisibilityIcon from '@mui/icons-material/Visibility';import DeleteIcon from '@mui/icons-material/Delete';import {useEffect,useState} from 'react';import {useDispatch} from 'react-redux';import {openModal} from '../../Api/Redux/Reducers/modalSlice';import {ApiService} from '../../Api/ApiService';
const fields=["taskCode","title","projectId","assignedTo","priority","status","completionPercentage","actualMinutes"];
const formatMinutes = value => { const minutes = Number(value) || 0; return `${Math.floor(minutes / 60)}h ${minutes % 60}m`; };
export default function Tasks(){const dispatch=useDispatch();const [rows,setRows]=useState([]);const [projects,setProjects]=useState([]);const [search,setSearch]=useState('');const [projectId,setProjectId]=useState('');const load=()=>ApiService.getTasks({search,projectId}).then(r=>setRows((r.data?.data||r.data).items||[]));useEffect(()=>{ApiService.getProjects({limit:100}).then(r=>{const data=r.data?.data||r.data||[];setProjects((data.items||data).map(item=>({value:item._id,label:item.name})));}).catch(()=>setProjects([]));},[]);useEffect(()=>{load()},[search,projectId]);const modal=(record,view=false)=>dispatch(openModal({title:(view?'View':record?'Edit':'Create')+' Tasks',component:view?'TASKS_VIEW':'TASKS_FORM',props:{resource:'tasks',fields,record,onSaved:load}}));return <Box><Box sx={{display:'flex',justifyContent:'space-between',mb:3}}><Box><Typography variant="h4" fontWeight={800}>Tasks</Typography><Typography color="text.secondary">Manage tasks.</Typography></Box><Button variant="contained" startIcon={<AddIcon/>} onClick={()=>modal()}>Create</Button></Box><Box sx={{display:'flex',gap:2,mb:2,flexWrap:'wrap',alignItems:'flex-end'}}><TextField size="small" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search" sx={{minWidth:220}}/><Box sx={{minWidth:240}}><CustomDropdown label="Project" name="projectId" value={projectId} options={projects} onChange={setProjectId} placeholder="All projects" /></Box></Box><CustomTable columns={[...fields.map((field) => ({ field, headerName: field === "actualMinutes" ? "Time Taken" : field, render: (row) => field === "actualMinutes" ? formatMinutes(row[field]) : (() => { const value = row[field]; return value && typeof value === "object" ? value.name || value._id || "—" : value || "—"; })() })), { field: "actions", headerName: "Actions", render: (row) => <Box sx={{ display: "flex" }}><IconButton onClick={() => modal(row, true)}><VisibilityIcon /></IconButton><IconButton onClick={() => modal(row)}><EditIcon /></IconButton><IconButton color="error" onClick={async () => { if (confirm("Delete this record?")) { await ApiService.deleteRecord("tasks", row._id); load(); } }}><DeleteIcon /></IconButton></Box> }]} rows={rows} emptyMessage="No records found" showSerialNumber /></Box>}

